### ISSUE TITLE
Icons Css

### ISSUE THREAD

**Issue by exodojaffar** [exodojaffar/TaskGoogleGui#4]
Nem todos os dispositivos suportam o CSS de icone que esta sendo usado.

Pesquisei e achei esse site de icones em CSS : https://css.gg/

**Comment by ExodoJaffar2** [comment]
o problema no icone é a importação do arquivo CSS.
Primeiro, aparentemente o arquivo era proibido ser baixado pelo firefox, pois ele era um arquivo misto.
Segundo, o arquivo da fonte não estava no servidor do git, entao não como baixado com a url passada no font-face.

Assim, a solução que penso e colocar o css no git e colocar a url de servidor de download da fonte, ou ver colocar a fonte no servidor e importar o css, veja qual é o melhor.
Esse css funciona
`@font-face {
  font-family: 'foundation-icons';
  src: url('https://mozilla.github.io/foundation-icons/assets/foundation-icons.woff') format('woff');
  font-weight: normal;
  font-style: normal;
}

[class^="icon-"]:before, [class*=" icon-"]:before {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: 'foundation-icons' !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  margin-right: 3px;
  position: relative;
  top: 1px;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-access:before {
  content: "\e900";
}
.icon-airplane:before {
  content: "\e901";
}
.icon-arrow-down:before {
  content: "\e902";
}
.icon-book:before {
  content: "\e903";
}
.icon-bookmark-large-flat:before {
  content: "\e904";
}
.icon-bookmark-small:before {
  content: "\e905";
}
.icon-bookmark:before {
  content: "\e906";
}
.icon-brain:before {
  content: "\e907";
}
.icon-calendar:before {
  content: "\e908";
}
.icon-certificate:before {
  content: "\e909";
}
.icon-checkmark-circle:before {
  content: "\e90a";
}
.icon-checkmark:before {
  content: "\e90b";
}
.icon-circle-clubs:before {
  content: "\e90c";
}
.icon-circle-tools:before {
  content: "\e90d";
}
.icon-clock:before {
  content: "\e90e";
}
.icon-close-x:before {
  content: "\e90f";
}
.icon-code-of-conduct:before {
  content: "\e910";
}
.icon-community:before {
  content: "\e911";
}
.icon-connected-people:before {
  content: "\e912";
}
.icon-creative-commons-solid:before {
  content: "\e913";
}
.icon-creative-commons:before {
  content: "\e914";
}
.icon-document-page:before {
  content: "\e915";
}
.icon-download-cloud:before {
  content: "\e916";
}
.icon-email:before {
  content: "\e917";
}
.icon-envelope-letter:before {
  content: "\e918";
}
.icon-envelope-outline:before {
  content: "\e919";
}
.icon-facebook:before {
  content: "\e91a";
}
.icon-flag-bent:before {
  content: "\e91b";
}
.icon-flag:before {
  content: "\e91c";
}
.icon-flowerhands:before {
  content: "\e91d";
}
.icon-github:before {
  content: "\e91e";
}
.icon-globe:before {
  content: "\e91f";
}
.icon-hamburger-menu-close:before {
  content: "\e920";
}
.icon-hamburger-menu:before {
  content: "\e921";
}
.icon-heart:before {
  content: "\e922";
}
.icon-holding-doc:before {
  content: "\e923";
}
.icon-icon-community:before {
  content: "\e924";
}
.icon-info-i:before {
  content: "\e925";
}
.icon-inspector-arrow:before {
  content: "\e926";
}
.icon-institution:before {
  content: "\e927";
}
.icon-learning-about-us:before {
  content: "\e928";
}
.icon-list-items:before {
  content: "\e929";
}
.icon-lock:before {
  content: "\e92a";
}
.icon-lunchbox:before {
  content: "\e92b";
}
.icon-map-marker:before {
  content: "\e92c";
}
.icon-minus:before {
  content: "\e92d";
}
.icon-mobile-phone:before {
  content: "\e92e";
}
.icon-monitor:before {
  content: "\e92f";
}
.icon-moon:before {
  content: "\e930";
}
.icon-mozfest-logo:before {
  content: "\e931";
}
.icon-mozilla-logo:before {
  content: "\e932";
}
.icon-open-book:before {
  content: "\e933";
}
.icon-page-with-bookmark:before {
  content: "\e934";
}
.icon-pencil-hand:before {
  content: "\e935";
}
.icon-pencil:before {
  content: "\e936";
}
.icon-plus:before {
  content: "\e937";
}
.icon-quesion-mark-outline:before {
  content: "\e938";
}
.icon-question-mark:before {
  content: "\e939";
}
.icon-redo:before {
  content: "\e93a";
}
.icon-refresh:before {
  content: "\e93b";
}
.icon-ribbon:before {
  content: "\e93c";
}
.icon-science-drop-double:before {
  content: "\e93d";
}
.icon-science-drop:before {
  content: "\e93e";
}
.icon-share:before {
  content: "\e93f";
}
.icon-sign-out:before {
  content: "\e940";
}
.icon-skill-collaboration:before {
  content: "\e941";
}
.icon-skill-communication:before {
  content: "\e942";
}
.icon-skill-creativity:before {
  content: "\e943";
}
.icon-skill-participate:before {
  content: "\e944";
}
.icon-skill-problem-solving:before {
  content: "\e945";
}
.icon-skill-read:before {
  content: "\e946";
}
.icon-skill-write:before {
  content: "\e947";
}
.icon-speech-bubble:before {
  content: "\e948";
}
.icon-speech-bubbles:before {
  content: "\e949";
}
.icon-sun:before {
  content: "\e94a";
}
.icon-three-persons:before {
  content: "\e94b";
}
.icon-trash-can:before {
  content: "\e94c";
}
.icon-triangle-left:before {
  content: "\e94d";
}
.icon-triangle-right:before {
  content: "\e94e";
}
.icon-twitter-outline:before {
  content: "\e94f";
}
.icon-twitter:before {
  content: "\e950";
}
.icon-undo:before {
  content: "\e951";
}
.icon-weblit-map:before {
  content: "\e952";
}

`

**Comment by exodojaffar** [comment]
Ta feito
Bjs
